document.writeln("<footer style=\"margin-top:70px\">");
document.writeln("<link href=\"frontend/css/footer.css\" rel=\"stylesheet\">");
document.writeln("<!--页尾波浪-->");
document.writeln("<div class=\"waves\">");
document.writeln("    <div class=\"wave\" id=\"wave1\"></div>");
document.writeln("    <div class=\"wave\" id=\"wave2\"></div>");
document.writeln("    <div class=\"wave\" id=\"wave3\"></div>");
document.writeln("    <div class=\"wave\" id=\"wave4\"></div>");
document.writeln("</div>");
document.writeln("<!--内容-->");
document.writeln("<div class=\"ui four column grid\" style=\"color:black\">");
document.writeln("    <div class=\"column\">");
document.writeln("        <div class=\"ui inverted circular segment\"");
document.writeln("            style=\"background-color:transparent;border-color:transparent!important\">");
document.writeln("            <a href=\"frontend/时间轴/Milestone.html\" style=\"\">");
document.writeln("                <h4>");
document.writeln("                    Website Milestone");
document.writeln("                </h4>");
document.writeln("            </a>");
document.writeln("            <p class=\"content\">");
document.writeln("");
document.writeln("            </p>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("");
document.writeln("    <div class=\"column\">");
document.writeln("        <div class=\"ui inverted circular segment\"");
document.writeln("            style=\"background-color:transparent;border-color:transparent!important\">");
document.writeln("            <h4 style=\"color:black\">");
document.writeln("                Picture Repository");
document.writeln("            </h4>");
document.writeln("            <p class=\"content\">");
document.writeln("");
document.writeln("            </p>");
document.writeln("        </div>");
document.writeln("    </div>");
document.writeln("    <div class=\"column\">");
document.writeln("        <div class=\"ui inverted circular segment\"");
document.writeln("            style=\"background-color:transparent;border-color:transparent!important\">");
document.writeln("            <h4 style=\"color:black\">");
document.writeln("                Contact us");
document.writeln("            </h4>");
document.writeln("            <p class=\"content\">");
document.writeln("");
document.writeln("            </p>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("");
document.writeln("    <div class=\"column\">");
document.writeln("        <div class=\"ui inverted circular segment\"");
document.writeln("            style=\"background-color:transparent;border-color:transparent!important\">");
document.writeln("            <h4 style=\"color:black\">");
document.writeln("                Relative Links");
document.writeln("            </h4>");
document.writeln("        </div>");
document.writeln("");
document.writeln("    </div>");
document.writeln("</div>");
document.writeln("<p class=\"footer_p\">&copy;2022 - <a href=\"frontend/underneath_decoration/skystar.html\"");
document.writeln("        style=\"color:black\"><strong>Alpha College</strong></a> All rights reserved</p>");
document.writeln("</footer>");
document.writeln("<script type=\"mouble\" src=\"https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js\"></script>");
document.writeln("<script nomodule src=\"https://unpkg.com/ionicons@5.5.2/dist/ionicons/ionicons.esm.js\"></script>");
