document.writeln("		<header><!--导航栏-->");
document.writeln("			<div class=\"ui yellow labeled fixed borderless menu\" style=\"height:80px\">");
document.writeln("				<a href=\"frontend/underneath_decoration/skystar.html\" class=\"item\">");
document.writeln("					<img class=\"ui small image icon2\" src=\"image/logo.jpg\">");
document.writeln("				</a>");
document.writeln("");
document.writeln("				<a href=\"index.html\" class=\"active item navigator\">");
document.writeln("					<i class=\"large home icon\"></i>");
document.writeln("					Home");
document.writeln("				</a>");
document.writeln("				<a href=\"frontend/html/notification.html\" class=\"item navigator\">");
document.writeln("					<i class=\"large comment alternate icon\"></i>");
document.writeln("					Notification");
document.writeln("				</a>");
document.writeln("				<div class=\"item\" style=\"\">");
document.writeln("					<div class=\"ui dropdown labeled icon button\"");
document.writeln("						style=\"background-color:white;margin: 0px !important;border:0px!important\">");
document.writeln("						<i class=\"large pencil alternate icon button\"");
document.writeln("							style=\"background-color:white;color: #7d97df!important;\"></i>");
document.writeln("						<a href=\"frontend/html/meetingsummary.html\" class=\"item navigator\"");
document.writeln("							style=\"border-bottom: none;padding: 0px !important;\">Journal</a>");
document.writeln("						<div class=\"menu\"");
document.writeln("							style=\"color: #7d97df;padding: 0px !important;border: 0px !important;margin: 0px !important;\">");
document.writeln("							<a href=\"frontend/html/meetingsummary.html\" class=\"ui button item navigator\"");
document.writeln("								style=\"color:#7d97df!important;margin: 0px !important;border:0px!important\">Meeting");
document.writeln("								Summary</a>");
document.writeln("							<a href=\"frontend/html/collegeactivity.html\" class=\"ui button item navigator\"");
document.writeln("								style=\"color:#7d97df!important;margin: 0px !important;border:0px!important\">College");
document.writeln("								Activity</a>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("				<a href=\"frontend/html/blog.html\" class=\"item navigator\">");
document.writeln("					<i class=\"large paper plane icon\"></i>");
document.writeln("					Blog");
document.writeln("				</a>");
document.writeln("				<a href=\"frontend/html/forum.html\" class=\"item navigator\" style=\"margin-left: 15px !important;\">");
document.writeln("					<i class=\"large comments icon\"></i>Forum</a>");
document.writeln("				<div class=\"item\">");
document.writeln("					<div class=\"ui dropdown labeled icon button\"");
document.writeln("						style=\"background-color:white;margin: 0px !important;border:0px!important\">");
document.writeln("						<i class=\"large users icon button\" style=\"background-color:white;color: #7d97df!important;\"></i>");
document.writeln("						<a href=\"frontend/html/people.html\" class=\"item navigator\"");
document.writeln("							style=\"border-bottom: none;padding: 0px !important;\">People</a>");
document.writeln("						<div class=\"menu\" style=\"color: #7d97df;border: 0px !important\">");
document.writeln("							<a href=\"frontend/html/people.html#aboutcollege\" class=\"ui button item navigator\"");
document.writeln("								style=\"color:#7d97df!important;margin: 0px !important;border:0px!important;\">");
document.writeln("								Alpha College</a>");
document.writeln("							<a href=\"frontend/html/people.html\" class=\"ui button item navigator\"");
document.writeln("								style=\"color:#7d97df!important;margin: 0px !important;border:0px!important;\">");
document.writeln("								College Members</a>");
document.writeln("						</div>");
document.writeln("					</div>");
document.writeln("				</div>");
document.writeln("				<!--置右部分-->");
document.writeln("				<div class=\"right fixed menu\" style=\"z-index:999!important\">");
document.writeln("					<div class=\"ui right aligned category search item\">");
document.writeln("						<div class=\"ui transparent icon input\">");
document.writeln("							<input class=\"prompt\" type=\"text\" placeholder=\"Search\">");
document.writeln("							<i class=\"search link icon\"");
document.writeln("								style=\"margin-bottom:20px!important;margin-top:0px!important\"></i>");
document.writeln("						</div>");
document.writeln("						<div class=\"results\"></div>");
document.writeln("					</div>");
document.writeln("					<!--<a href=\"https://westlake.edu.cn\" class=\"ui right floated header\">");
document.writeln("					<img class=\"ui small image icon1\" src=\"image/Westlakelogo.jpg\">");
document.writeln("				</a>-->");
document.writeln("					<div class=\"tiny ui buttons\" style=\"margin:20px 0 20px 0;\">");
document.writeln("						<button class=\"tiny ui button \">中文</button>");
document.writeln("						<div class=\"or\"></div>");
document.writeln("						<button class=\"tiny ui button active yellow button\">English</button>");
document.writeln("					</div>");
document.writeln("");
document.writeln("				</div>");
document.writeln("			</div>");
document.writeln("		</header>");

